// <auto-generated />
using System;
using JMT.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JMT.Migrations
{
    [DbContext(typeof(DeveloperdbContext))]
    partial class DeveloperdbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JMT.ViewModel.TCustomerInbox", b =>
                {
                    b.Property<int>("CustomerInboxID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CustomerInboxID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChatMessage")
                        .IsRequired()
                        .HasColumnName("ChatMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<int>("CustomerID")
                        .HasColumnName("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnName("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("FirstName")
                        .HasColumnName("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("LastName")
                        .HasColumnName("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<DateTime>("MessageDate")
                        .HasColumnName("MessageDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnName("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.HasKey("CustomerInboxID");

                    b.ToTable("TCustomerInbox");
                });

            modelBuilder.Entity("JMT.ViewModel.TCustomerPending", b =>
                {
                    b.Property<int>("CustomerPendingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CustomerPendingID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPStatus")
                        .HasColumnName("CPStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<int>("CustomerID")
                        .HasColumnName("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnName("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOffered")
                        .HasColumnName("DateOffered")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeveloperID")
                        .HasColumnName("DeveloperID")
                        .HasColumnType("int");

                    b.Property<string>("OrderDesc")
                        .IsRequired()
                        .HasColumnName("OrderDesc")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("PriceOffered")
                        .IsRequired()
                        .HasColumnName("PriceOffered")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnName("Requirements")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.HasKey("CustomerPendingID");

                    b.ToTable("TCustomerPending");
                });

            modelBuilder.Entity("JMT.ViewModel.TCustomers", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CustomerID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DashboardColor")
                        .IsRequired()
                        .HasColumnName("DashboardColor")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnName("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Photo")
                        .HasColumnName("Photo")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<int>("RoleID")
                        .HasColumnName("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("SideBarColor")
                        .IsRequired()
                        .HasColumnName("SideBarColor")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.HasKey("CustomerID");

                    b.ToTable("TCustomers");
                });

            modelBuilder.Entity("JMT.ViewModel.TDeveloperDeclined", b =>
                {
                    b.Property<int>("DeveloperDeclinedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeveloperDeclinedID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeclineReason")
                        .HasColumnName("DeclineReason")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<DateTime>("DeclinedDate")
                        .HasColumnName("DeclinedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeveloperID")
                        .HasColumnName("DeveloperID")
                        .HasColumnType("int");

                    b.Property<int>("DeveloperPendingID")
                        .HasColumnName("DeveloperPendingID")
                        .HasColumnType("int");

                    b.Property<string>("OrderDescription")
                        .HasColumnName("OrderDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.HasKey("DeveloperDeclinedID");

                    b.ToTable("TDeveloperDeclined");
                });

            modelBuilder.Entity("JMT.ViewModel.TDeveloperInbox", b =>
                {
                    b.Property<int>("DeveloperInboxID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeveloperInboxID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChatMessage")
                        .HasColumnName("ChatMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<int>("DeveloperID")
                        .HasColumnName("DeveloperID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnName("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("FirstName")
                        .HasColumnName("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("LastName")
                        .HasColumnName("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<DateTime>("MessageDate")
                        .HasColumnName("MessageDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnName("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.HasKey("DeveloperInboxID");

                    b.ToTable("TDeveloperInbox");
                });

            modelBuilder.Entity("JMT.ViewModel.TDeveloperLinks", b =>
                {
                    b.Property<int>("DeveloperLinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeveloperLinkID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeveloperID")
                        .HasColumnName("DeveloperID")
                        .HasColumnType("int");

                    b.Property<string>("HyperLink")
                        .IsRequired()
                        .HasColumnName("HyperLink")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("ViewType")
                        .IsRequired()
                        .HasColumnName("ViewType")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.HasKey("DeveloperLinkID");

                    b.ToTable("TDeveloperLinks");
                });

            modelBuilder.Entity("JMT.ViewModel.TDeveloperNotes", b =>
                {
                    b.Property<int>("DeveloperNoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeveloperNoteID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeveloperID")
                        .HasColumnName("DeveloperID")
                        .HasColumnType("int");

                    b.Property<string>("NoteContent")
                        .HasColumnName("NoteContent")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Title")
                        .HasColumnName("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("ViewType")
                        .HasColumnName("ViewType")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.HasKey("DeveloperNoteID");

                    b.ToTable("TDeveloperNotes");
                });

            modelBuilder.Entity("JMT.ViewModel.TDeveloperPending", b =>
                {
                    b.Property<int>("DeveloperPendingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeveloperPendingID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Budget")
                        .HasColumnName("Budget")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<int>("CustomerID")
                        .HasColumnName("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("DPStatus")
                        .HasColumnName("DPStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnName("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnName("DateRequested")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeveloperID")
                        .HasColumnName("DeveloperID")
                        .HasColumnType("int");

                    b.Property<string>("OrderDesc")
                        .HasColumnName("OrderDesc")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Requirements")
                        .HasColumnName("Requirements")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.HasKey("DeveloperPendingID");

                    b.ToTable("TDeveloperPending");
                });

            modelBuilder.Entity("JMT.ViewModel.TDeveloperProjects", b =>
                {
                    b.Property<int>("DeveloperProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeveloperProjectID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasColumnName("Alt")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<int>("DeveloperID")
                        .HasColumnName("DeveloperID")
                        .HasColumnType("int");

                    b.Property<string>("PreviewImageSrc")
                        .IsRequired()
                        .HasColumnName("PreviewImageSrc")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("ThumbnailImageSrc")
                        .IsRequired()
                        .HasColumnName("ThumbnailImageSrc")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.HasKey("DeveloperProjectID");

                    b.ToTable("TDeveloperProjects");
                });

            modelBuilder.Entity("JMT.ViewModel.TDeveloperTasks", b =>
                {
                    b.Property<int>("DeveloperTaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeveloperTaskID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<int>("DeveloperID")
                        .HasColumnName("DeveloperID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnName("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<int>("OrderID")
                        .HasColumnName("OrderID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnName("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Title")
                        .HasColumnName("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.HasKey("DeveloperTaskID");

                    b.ToTable("TDeveloperTasks");
                });

            modelBuilder.Entity("JMT.ViewModel.TDevelopers", b =>
                {
                    b.Property<int>("DeveloperID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeveloperID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Certification")
                        .IsRequired()
                        .HasColumnName("Certification")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("DashboardColor")
                        .IsRequired()
                        .HasColumnName("DashboardColor")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnName("Education")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("PLanguages")
                        .IsRequired()
                        .HasColumnName("PLanguages")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnName("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Photo")
                        .HasColumnName("Photo")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<int>("RoleID")
                        .HasColumnName("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("SideBarColor")
                        .IsRequired()
                        .HasColumnName("SideBarColor")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnName("Skills")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.HasKey("DeveloperID");

                    b.ToTable("TDevelopers");
                });

            modelBuilder.Entity("JMT.ViewModel.TOrders", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("OrderID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnName("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerID")
                        .HasColumnName("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("CustomerReview")
                        .HasColumnName("CustomerReview")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnName("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeveloperID")
                        .HasColumnName("DeveloperID")
                        .HasColumnType("int");

                    b.Property<string>("OrderDesc")
                        .HasColumnName("OrderDesc")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Price")
                        .HasColumnName("Price")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Rating")
                        .HasColumnName("Rating")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnName("Requirements")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Status")
                        .HasColumnName("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.HasKey("OrderID");

                    b.ToTable("TOrders");
                });

            modelBuilder.Entity("JMT.ViewModel.TRMDeveloper", b =>
                {
                    b.Property<int>("RMDeveloperID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RMDeveloperID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeveloperID")
                        .HasColumnName("DeveloperID")
                        .HasColumnType("int");

                    b.Property<int>("ResourceManagerID")
                        .HasColumnName("ResourceManagerID")
                        .HasColumnType("int");

                    b.HasKey("RMDeveloperID");

                    b.ToTable("TRMDeveloper");
                });

            modelBuilder.Entity("JMT.ViewModel.TRMInbox", b =>
                {
                    b.Property<int>("RMInboxID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RMInboxID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChatMessage")
                        .IsRequired()
                        .HasColumnName("ChatMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Email")
                        .HasColumnName("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("FirstName")
                        .HasColumnName("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("LastName")
                        .HasColumnName("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<DateTime>("MessageDate")
                        .HasColumnName("MessageDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResourceManagerID")
                        .HasColumnName("ResourceManagerID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnName("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.HasKey("RMInboxID");

                    b.ToTable("TRMInbox");
                });

            modelBuilder.Entity("JMT.ViewModel.TResourceManagerLinks", b =>
                {
                    b.Property<int>("ResourceManagerLinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ResourceManagerLinkID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HyperLink")
                        .IsRequired()
                        .HasColumnName("HyperLink")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<int>("ResourceManagerID")
                        .HasColumnName("ResourceManagerID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("ViewType")
                        .IsRequired()
                        .HasColumnName("ViewType")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.HasKey("ResourceManagerLinkID");

                    b.ToTable("TResourceManagerLinks");
                });

            modelBuilder.Entity("JMT.ViewModel.TResourceManagerNotes", b =>
                {
                    b.Property<int>("ResourceManagerNotesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ResourceManagerNotesID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NoteContent")
                        .HasColumnName("NoteContent")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<int>("ResourceManagerID")
                        .HasColumnName("ResourceManagerID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnName("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("ViewType")
                        .HasColumnName("ViewType")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.HasKey("ResourceManagerNotesID");

                    b.ToTable("TResourceManagerNotes");
                });

            modelBuilder.Entity("JMT.ViewModel.TResourceManagers", b =>
                {
                    b.Property<int>("ResourceManagerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ResourceManagerID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DashboardColor")
                        .IsRequired()
                        .HasColumnName("DashboardColor")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnName("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<string>("Photo")
                        .HasColumnName("Photo")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.Property<int>("RoleID")
                        .HasColumnName("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("SideBarColor")
                        .IsRequired()
                        .HasColumnName("SideBarColor")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.HasKey("ResourceManagerID");

                    b.ToTable("TResourceManagers");
                });

            modelBuilder.Entity("JMT.ViewModel.TRoles", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RoleID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleDesc")
                        .IsRequired()
                        .HasColumnName("RoleDesc")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(1073741791);

                    b.HasKey("RoleID");

                    b.ToTable("TRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
